Fix probes when server.servlet.contextPath is set
IllegalArgumentException: ContextPath must start with '/' and not end with '/'
Use trimSuffix helm function to remove any trailing slash "/"